sudo: true

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

env:
  - SBT_OPTS = -XX:MaxPermSize=1024M -XX:+UseConcMarkSweepGC -XX:+CMSPermGenSweepingEnabled -XX:+CMSClassUnloadingEnabled

script:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.1.2/2.12-1.1.2) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
  - amm project/scripts/CheckExampleVersion.sc
  - cd examples/api_examples/ && sbt "+ runMain example.ExampleApiApp"
  - sbt "+ runMain example.TokenApp" && cd ../../
  - sbt clean tut coverage test coverageReport


after_success:
  - bash <(curl -s https://codecov.io/bash)

scala:
  - 2.12.1

jdk:
  - oraclejdk8

branches:
  only:
    - master
